import { useState, useEffect } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  FileText,
  Calendar,
  BarChart3,
  Clock,
  BookOpen,
  Users,
  Sparkles,
  ChevronRight,
  Download,
  Trash2,
  RefreshCw,
  Filter,
  ChevronDown,
  Loader2,
  CheckCircle2,
  AlertCircle,
  TrendingUp,
  PieChart,
  Activity,
  MoreHorizontal,
  Share2,
  Star,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { ScrollArea } from '@/components/ui/scroll-area';
import { toast } from 'sonner';
import { apiClient, getErrorMessage } from '@/lib/api-client';
import { cn } from '@/lib/utils';
import { motion, AnimatePresence } from 'framer-motion';

// ============================================
// 类型定义
// ============================================
type ReportType = 'weekly' | 'monthly' | 'semester' | 'subject' | 'time' | 'behavior' | 'custom';

interface ReportTypeConfig {
  id: ReportType;
  name: string;
  description: string;
  icon: React.ReactNode;
  color: string;
  autoGenerate?: boolean;
}

interface Report {
  id: number;
  type: ReportType;
  title: string;
  content: ReportContent;
  childId?: number;
  childName?: string;
  startDate: string;
  endDate: string;
  createdAt: string;
  isAutoGenerated: boolean;
  isFavorite?: boolean;
}

interface ReportContent {
  summary: string;
  highlights: string[];
  suggestions: string[];
  predictions?: string;
  dataAnalysis: {
    completionRate: number;
    totalTasks: number;
    totalTime: number;
    subjectDistribution: Record<string, number>;
    dailyTrend: Array<{ day: string; rate: number }>;
  };
}

interface Child {
  id: number;
  name: string;
  avatar: string;
}

// ============================================
// 报告类型配置
// ============================================
const REPORT_TYPES: ReportTypeConfig[] = [
  {
    id: 'weekly',
    name: '周报',
    description: '每周学习情况总结与分析',
    icon: <Calendar className="w-5 h-5" />,
    color: 'bg-blue-500',
    autoGenerate: true,
  },
  {
    id: 'monthly',
    name: '月报',
    description: '月度学习成果与趋势分析',
    icon: <Calendar className="w-5 h-5" />,
    color: 'bg-purple-500',
    autoGenerate: true,
  },
  {
    id: 'semester',
    name: '学期报',
    description: '学期整体表现总结',
    icon: <FileText className="w-5 h-5" />,
    color: 'bg-indigo-500',
    autoGenerate: true,
  },
  {
    id: 'subject',
    name: '学科分析',
    description: '特定学科的深入分析',
    icon: <BookOpen className="w-5 h-5" />,
    color: 'bg-emerald-500',
  },
  {
    id: 'time',
    name: '时间分析',
    description: '学习效率与时间管理分析',
    icon: <Clock className="w-5 h-5" />,
    color: 'bg-amber-500',
  },
  {
    id: 'behavior',
    name: '行为分析',
    description: '学习习惯与行为模式分析',
    icon: <Activity className="w-5 h-5" />,
    color: 'bg-rose-500',
  },
  {
    id: 'custom',
    name: '自定义分析',
    description: '自定义时间范围与维度',
    icon: <BarChart3 className="w-5 h-5" />,
    color: 'bg-cyan-500',
  },
];

// ============================================
// API 函数
// ============================================
async function fetchReports(type?: ReportType, childId?: number): Promise<Report[]> {
  const params = new URLSearchParams();
  if (type) params.append('type', type);
  if (childId) params.append('childId', childId.toString());
  const { data } = await apiClient.get(`/reports?${params}`);
  return data.data;
}

async function fetchReport(id: number): Promise<Report> {
  const { data } = await apiClient.get(`/reports/${id}`);
  return data.data;
}

async function generateReport(params: {
  type: ReportType;
  childId?: number;
  startDate: string;
  endDate: string;
  subjects?: string[];
}): Promise<Report> {
  const { data } = await apiClient.post('/reports/generate', params);
  return data.data;
}

async function deleteReport(id: number): Promise<void> {
  await apiClient.delete(`/reports/${id}`);
}

async function toggleFavorite(id: number, isFavorite: boolean): Promise<void> {
  await apiClient.put(`/reports/${id}/favorite`, { isFavorite });
}

async function fetchChildren(): Promise<Child[]> {
  const { data } = await apiClient.get('/children');
  return data.data;
}

// ============================================
// 报告卡片组件
// ============================================
function ReportCard({
  report,
  onClick,
  onDelete,
  onToggleFavorite,
}: {
  report: Report;
  onClick: () => void;
  onDelete: (e: React.MouseEvent) => void;
  onToggleFavorite: (e: React.MouseEvent) => void;
}) {
  const reportType = REPORT_TYPES.find((t) => t.id === report.type);

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      whileHover={{ y: -2 }}
      className="cursor-pointer"
      onClick={onClick}
    >
      <Card className="border-0 shadow-md hover:shadow-lg transition-all">
        <CardContent className="p-4">
          <div className="flex items-start gap-4">
            <div
              className={cn(
                'w-12 h-12 rounded-xl flex items-center justify-center text-white shrink-0',
                reportType?.color || 'bg-gray-500'
              )}
            >
              {reportType?.icon}
            </div>
            <div className="flex-1 min-w-0">
              <div className="flex items-start justify-between gap-2">
                <div>
                  <h4 className="font-semibold text-gray-900 truncate">{report.title}</h4>
                  <p className="text-sm text-gray-500 mt-0.5">
                    {report.childName || '全部孩子'} · {new Date(report.createdAt).toLocaleDateString()}
                  </p>
                </div>
                <div className="flex items-center gap-1">
                  {report.isAutoGenerated && (
                    <Badge variant="secondary" className="text-xs">
                      自动生成
                    </Badge>
                  )}
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8"
                    onClick={onToggleFavorite}
                  >
                    <Star
                      className={cn(
                        'w-4 h-4',
                        report.isFavorite ? 'fill-yellow-400 text-yellow-400' : 'text-gray-400'
                      )}
                    />
                  </Button>
                </div>
              </div>
              <p className="text-sm text-gray-600 mt-2 line-clamp-2">{report.content.summary}</p>
              <div className="flex items-center gap-4 mt-3 text-xs text-gray-500">
                <span className="flex items-center gap-1">
                  <Calendar className="w-3.5 h-3.5" />
                  {new Date(report.startDate).toLocaleDateString()} -{' '}
                  {new Date(report.endDate).toLocaleDateString()}
                </span>
                <span className="flex items-center gap-1">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  完成率 {report.content.dataAnalysis.completionRate}%
                </span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  );
}

// ============================================
// 报告详情组件
// ============================================
function ReportDetail({
  report,
  onClose,
  onRegenerate,
}: {
  report: Report;
  onClose: () => void;
  onRegenerate: () => void;
}) {
  const reportType = REPORT_TYPES.find((t) => t.id === report.type);

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      className="h-full flex flex-col"
    >
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b">
        <div className="flex items-center gap-3">
          <div
            className={cn(
              'w-10 h-10 rounded-lg flex items-center justify-center text-white',
              reportType?.color || 'bg-gray-500'
            )}
          >
            {reportType?.icon}
          </div>
          <div>
            <h3 className="font-semibold text-lg">{report.title}</h3>
            <p className="text-sm text-gray-500">
              {report.childName || '全部孩子'} · {new Date(report.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={onRegenerate}>
            <RefreshCw className="w-4 h-4 mr-1" />
            重新生成
          </Button>
          <Button variant="outline" size="sm">
            <Download className="w-4 h-4 mr-1" />
            导出
          </Button>
          <Button variant="ghost" size="icon" onClick={onClose}>
            <ChevronRight className="w-5 h-5" />
          </Button>
        </div>
      </div>

      {/* Content */}
      <ScrollArea className="flex-1 p-6">
        <div className="space-y-6 max-w-3xl">
          {/* AI 分析摘要 */}
          <Card className="border-0 shadow-md bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50">
            <CardContent className="p-6">
              <div className="flex items-start gap-4">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-500 flex items-center justify-center shrink-0">
                  <Sparkles className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h4 className="font-semibold text-lg mb-2">AI 分析摘要</h4>
                  <p className="text-gray-700 leading-relaxed">{report.content.summary}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* 关键指标 */}
          <div className="grid grid-cols-3 gap-4">
            <Card className="border-0 shadow-sm">
              <CardContent className="p-4 text-center">
                <p className="text-sm text-gray-500 mb-1">完成率</p>
                <p className="text-3xl font-bold text-emerald-500">
                  {report.content.dataAnalysis.completionRate}%
                </p>
              </CardContent>
            </Card>
            <Card className="border-0 shadow-sm">
              <CardContent className="p-4 text-center">
                <p className="text-sm text-gray-500 mb-1">完成任务</p>
                <p className="text-3xl font-bold text-blue-500">
                  {report.content.dataAnalysis.totalTasks}
                </p>
              </CardContent>
            </Card>
            <Card className="border-0 shadow-sm">
              <CardContent className="p-4 text-center">
                <p className="text-sm text-gray-500 mb-1">学习时长</p>
                <p className="text-3xl font-bold text-purple-500">
                  {Math.round(report.content.dataAnalysis.totalTime / 60)}h
                </p>
              </CardContent>
            </Card>
          </div>

          {/* 亮点 */}
          {report.content.highlights.length > 0 && (
            <Card className="border-0 shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Star className="w-5 h-5 text-yellow-500" />
                  本周亮点
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <ul className="space-y-2">
                  {report.content.highlights.map((highlight, index) => (
                    <li key={index} className="flex items-start gap-2 text-sm">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 mt-0.5 shrink-0" />
                      <span className="text-gray-700">{highlight}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}

          {/* 改进建议 */}
          {report.content.suggestions.length > 0 && (
            <Card className="border-0 shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-blue-500" />
                  改进建议
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <ul className="space-y-2">
                  {report.content.suggestions.map((suggestion, index) => (
                    <li key={index} className="flex items-start gap-2 text-sm">
                      <AlertCircle className="w-4 h-4 text-amber-500 mt-0.5 shrink-0" />
                      <span className="text-gray-700">{suggestion}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}

          {/* 预测 */}
          {report.content.predictions && (
            <Card className="border-0 shadow-sm bg-gradient-to-r from-blue-50 to-indigo-50">
              <CardHeader className="pb-3">
                <CardTitle className="text-base flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-indigo-500" />
                  下周预测
                </CardTitle>
              </CardHeader>
              <CardContent className="pt-0">
                <p className="text-sm text-gray-700">{report.content.predictions}</p>
              </CardContent>
            </Card>
          )}
        </div>
      </ScrollArea>
    </motion.div>
  );
}

// ============================================
// 生成报告表单
// ============================================
function GenerateReportForm({
  onGenerate,
  isGenerating,
}: {
  onGenerate: (params: {
    type: ReportType;
    childId?: number;
    startDate: string;
    endDate: string;
  }) => void;
  isGenerating: boolean;
}) {
  const [selectedType, setSelectedType] = useState<ReportType>('weekly');
  const [selectedChild, setSelectedChild] = useState<number | undefined>();
  const [dateRange, setDateRange] = useState({
    start: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    end: new Date().toISOString().split('T')[0],
  });

  const { data: children } = useQuery({
    queryKey: ['children'],
    queryFn: fetchChildren,
  });

  const handleGenerate = () => {
    onGenerate({
      type: selectedType,
      childId: selectedChild,
      startDate: dateRange.start,
      endDate: dateRange.end,
    });
  };

  // 根据报告类型自动设置日期范围
  useEffect(() => {
    const now = new Date();
    let start = new Date();

    switch (selectedType) {
      case 'weekly':
        start = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        break;
      case 'monthly':
        start = new Date(now.getFullYear(), now.getMonth() - 1, now.getDate());
        break;
      case 'semester':
        start = new Date(now.getFullYear(), now.getMonth() - 3, now.getDate());
        break;
      default:
        break;
    }

    setDateRange({
      start: start.toISOString().split('T')[0],
      end: now.toISOString().split('T')[0],
    });
  }, [selectedType]);

  return (
    <div className="space-y-6">
      {/* 报告类型选择 */}
      <div>
        <h4 className="text-sm font-medium text-gray-700 mb-3">选择报告类型</h4>
        <div className="grid grid-cols-2 gap-3">
          {REPORT_TYPES.map((type) => (
            <button
              key={type.id}
              onClick={() => setSelectedType(type.id)}
              className={cn(
                'flex items-start gap-3 p-4 rounded-xl border-2 transition-all text-left',
                selectedType === type.id
                  ? 'border-primary bg-primary/5'
                  : 'border-gray-200 hover:border-gray-300'
              )}
            >
              <div
                className={cn(
                  'w-10 h-10 rounded-lg flex items-center justify-center text-white shrink-0',
                  type.color
                )}
              >
                {type.icon}
              </div>
              <div>
                <div className="flex items-center gap-2">
                  <span className="font-medium">{type.name}</span>
                  {type.autoGenerate && (
                    <Badge variant="secondary" className="text-xs">
                      自动
                    </Badge>
                  )}
                </div>
                <p className="text-xs text-gray-500 mt-1">{type.description}</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      {/* 孩子选择 */}
      {children && children.length > 0 && (
        <div>
          <h4 className="text-sm font-medium text-gray-700 mb-3">选择孩子</h4>
          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setSelectedChild(undefined)}
              className={cn(
                'px-4 py-2 rounded-full text-sm font-medium transition-all',
                !selectedChild
                  ? 'bg-primary text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              )}
            >
              全部
            </button>
            {children.map((child) => (
              <button
                key={child.id}
                onClick={() => setSelectedChild(child.id)}
                className={cn(
                  'px-4 py-2 rounded-full text-sm font-medium transition-all flex items-center gap-2',
                  selectedChild === child.id
                    ? 'bg-primary text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                )}
              >
                <span>{child.avatar}</span>
                <span>{child.name}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* 时间范围 */}
      <div>
        <h4 className="text-sm font-medium text-gray-700 mb-3">时间范围</h4>
        <div className="flex gap-3">
          <input
            type="date"
            value={dateRange.start}
            onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
            className="flex-1 px-3 py-2 border rounded-lg text-sm"
          />
          <span className="text-gray-400 self-center">至</span>
          <input
            type="date"
            value={dateRange.end}
            onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
            className="flex-1 px-3 py-2 border rounded-lg text-sm"
          />
        </div>
      </div>

      {/* 生成按钮 */}
      <Button
        onClick={handleGenerate}
        disabled={isGenerating}
        className="w-full"
        size="lg"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
            AI 分析中...
          </>
        ) : (
          <>
            <Sparkles className="w-5 h-5 mr-2" />
            生成 AI 分析报告
          </>
        )}
      </Button>
    </div>
  );
}

// ============================================
// 主组件
// ============================================
export default function ReportsPage() {
  const [selectedTab, setSelectedTab] = useState<'all' | ReportType>('all');
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const queryClient = useQueryClient();

  const { data: reports, isLoading } = useQuery({
    queryKey: ['reports', selectedTab],
    queryFn: () => fetchReports(selectedTab === 'all' ? undefined : selectedTab),
  });

  const generateMutation = useMutation({
    mutationFn: generateReport,
    onSuccess: (newReport) => {
      toast.success('报告生成成功');
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      setSelectedReport(newReport);
      setIsGenerating(false);
    },
    onError: (error) => {
      toast.error(`生成失败：${getErrorMessage(error)}`);
      setIsGenerating(false);
    },
  });

  const deleteMutation = useMutation({
    mutationFn: deleteReport,
    onSuccess: () => {
      toast.success('报告已删除');
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      if (selectedReport) {
        setSelectedReport(null);
      }
    },
    onError: (error) => toast.error(`删除失败：${getErrorMessage(error)}`),
  });

  const favoriteMutation = useMutation({
    mutationFn: ({ id, isFavorite }: { id: number; isFavorite: boolean }) =>
      toggleFavorite(id, isFavorite),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['reports'] });
    },
  });

  const handleGenerate = (params: {
    type: ReportType;
    childId?: number;
    startDate: string;
    endDate: string;
  }) => {
    setIsGenerating(true);
    generateMutation.mutate(params);
  };

  const filteredReports = reports?.filter((report) =>
    selectedTab === 'all' ? true : report.type === selectedTab
  );

  return (
    <div className="h-full flex">
      {/* Left Panel */}
      <div className="w-96 border-r bg-gray-50/50 flex flex-col">
        {/* Header */}
        <div className="p-4 border-b bg-white">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <FileText className="w-6 h-6 text-primary" />
            报告中心
          </h2>
          <p className="text-sm text-gray-500 mt-1">AI 驱动的学习分析报告</p>
        </div>

        {/* Generate Form */}
        <div className="p-4 border-b bg-white">
          <GenerateReportForm onGenerate={handleGenerate} isGenerating={isGenerating} />
        </div>

        {/* Report List */}
        <div className="flex-1 overflow-hidden flex flex-col">
          {/* Filter Tabs */}
          <div className="px-4 pt-4">
            <Tabs value={selectedTab} onValueChange={(v) => setSelectedTab(v as typeof selectedTab)}>
              <TabsList className="w-full">
                <TabsTrigger value="all" className="flex-1">
                  全部
                </TabsTrigger>
                <TabsTrigger value="weekly" className="flex-1">
                  周报
                </TabsTrigger>
                <TabsTrigger value="monthly" className="flex-1">
                  月报
                </TabsTrigger>
              </TabsList>
            </Tabs>
          </div>

          {/* List */}
          <ScrollArea className="flex-1 p-4">
            {isLoading ? (
              <div className="space-y-3">
                {[1, 2, 3].map((i) => (
                  <Skeleton key={i} className="h-32 rounded-xl" />
                ))}
              </div>
            ) : filteredReports?.length === 0 ? (
              <div className="text-center py-12">
                <FileText className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-gray-500">暂无报告</p>
                <p className="text-sm text-gray-400 mt-1">点击上方按钮生成报告</p>
              </div>
            ) : (
              <div className="space-y-3">
                <AnimatePresence mode="popLayout">
                  {filteredReports?.map((report) => (
                    <ReportCard
                      key={report.id}
                      report={report}
                      onClick={() => setSelectedReport(report)}
                      onDelete={(e) => {
                        e.stopPropagation();
                        deleteMutation.mutate(report.id);
                      }}
                      onToggleFavorite={(e) => {
                        e.stopPropagation();
                        favoriteMutation.mutate({ id: report.id, isFavorite: !report.isFavorite });
                      }}
                    />
                  ))}
                </AnimatePresence>
              </div>
            )}
          </ScrollArea>
        </div>
      </div>

      {/* Right Panel - Report Detail */}
      <div className="flex-1 bg-white">
        <AnimatePresence mode="wait">
          {selectedReport ? (
            <ReportDetail
              key={selectedReport.id}
              report={selectedReport}
              onClose={() => setSelectedReport(null)}
              onRegenerate={() =>
                handleGenerate({
                  type: selectedReport.type,
                  childId: selectedReport.childId,
                  startDate: selectedReport.startDate,
                  endDate: selectedReport.endDate,
                })
              }
            />
          ) : (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="h-full flex items-center justify-center"
            >
              <div className="text-center">
                <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <FileText className="w-10 h-10 text-gray-400" />
                </div>
                <h3 className="text-lg font-medium text-gray-900">选择报告查看详情</h3>
                <p className="text-sm text-gray-500 mt-1">或生成新的 AI 分析报告</p>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
