import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  Activity,
  BarChart3,
  BookOpen,
  Calendar,
  CheckCircle2,
  Clock3,
  Download,
  Eye,
  FileText,
  GraduationCap,
  Loader2,
  MoreHorizontal,
  RefreshCw,
  Sparkles,
  Star,
  Trash2,
  UserRound,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { DatePicker } from '@/components/ui/date-picker';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { apiClient, getErrorMessage } from '@/lib/api-client';
import { cn } from '@/lib/utils';
import { useSelectedChild } from '@/contexts/SelectedChildContext';
import { PageToolbar, PageToolbarTitle } from '@/components/parent/PageToolbar';

type ReportType = 'weekly' | 'monthly' | 'semester' | 'subject' | 'time' | 'behavior' | 'custom';

interface ReportTypeConfig {
  id: ReportType;
  name: string;
  shortName: string;
  description: string;
  icon: LucideIcon;
  tone: string;
  badge: string;
  autoGenerate?: boolean;
}

interface Report {
  id: number;
  type: ReportType;
  title: string;
  content: ReportContent;
  childId?: number;
  childName?: string;
  startDate: string;
  endDate: string;
  createdAt: string;
  isAutoGenerated: boolean;
  isFavorite?: boolean;
}

interface ReportContent {
  summary: string;
  highlights: string[];
  suggestions: string[];
  predictions?: string;
  dataAnalysis: {
    completionRate: number;
    totalTasks: number;
    totalTime: number;
    subjectDistribution: Record<string, number>;
    dailyTrend: Array<{ day: string; rate: number }>;
  };
}

type DateRange = {
  start: string;
  end: string;
};

const REPORT_TYPES: ReportTypeConfig[] = [
  {
    id: 'weekly',
    name: '周报',
    shortName: '周报',
    description: '每周学习情况总结与分析',
    icon: Calendar,
    tone: 'bg-blue-50 text-blue-600',
    badge: 'bg-blue-50 text-blue-700',
    autoGenerate: true,
  },
  {
    id: 'monthly',
    name: '月报',
    shortName: '月报',
    description: '月度学习成果趋势分析',
    icon: Calendar,
    tone: 'bg-violet-50 text-violet-600',
    badge: 'bg-violet-50 text-violet-700',
    autoGenerate: true,
  },
  {
    id: 'semester',
    name: '学期报',
    shortName: '学期报',
    description: '学期整体表现总结',
    icon: FileText,
    tone: 'bg-indigo-50 text-indigo-600',
    badge: 'bg-indigo-50 text-indigo-700',
    autoGenerate: true,
  },
  {
    id: 'subject',
    name: '学科分析',
    shortName: '学科',
    description: '特定学科的深入分析',
    icon: BookOpen,
    tone: 'bg-emerald-50 text-emerald-600',
    badge: 'bg-emerald-50 text-emerald-700',
  },
  {
    id: 'time',
    name: '时间分析',
    shortName: '时间',
    description: '学习效率与时间管理分析',
    icon: Clock3,
    tone: 'bg-orange-50 text-orange-600',
    badge: 'bg-orange-50 text-orange-700',
  },
  {
    id: 'behavior',
    name: '行为分析',
    shortName: '行为',
    description: '学习习惯与节奏分析',
    icon: Activity,
    tone: 'bg-rose-50 text-rose-600',
    badge: 'bg-rose-50 text-rose-700',
  },
  {
    id: 'custom',
    name: '自定义分析',
    shortName: '自定义',
    description: '自定义范围与维度分析',
    icon: BarChart3,
    tone: 'bg-cyan-50 text-cyan-600',
    badge: 'bg-cyan-50 text-cyan-700',
  },
];

const DIMENSIONS = ['任务完成', '学习时长', '阅读情况', '学科分布', '行为节奏'];

async function fetchReports(type?: ReportType, childId?: number): Promise<Report[]> {
  const params = new URLSearchParams();
  if (type) params.append('type', type);
  if (childId) params.append('childId', childId.toString());
  const { data } = await apiClient.get(`/reports?${params}`);
  return data.data || [];
}

async function generateReport(params: {
  type: ReportType;
  childId?: number;
  startDate: string;
  endDate: string;
  subjects?: string[];
}): Promise<Report> {
  const { data } = await apiClient.post('/reports/generate', params);
  return data.data;
}

async function deleteReport(id: number): Promise<void> {
  await apiClient.delete(`/reports/${id}`);
}

async function toggleFavorite(id: number, isFavorite: boolean): Promise<void> {
  await apiClient.put(`/reports/${id}/favorite`, { isFavorite });
}

function toDateInput(date: Date) {
  return date.toISOString().split('T')[0];
}

function getRangeForType(type: ReportType): DateRange {
  const end = new Date();
  const start = new Date(end);

  if (type === 'monthly') {
    start.setDate(end.getDate() - 30);
  } else if (type === 'semester') {
    start.setMonth(end.getMonth() - 4);
  } else {
    start.setDate(end.getDate() - 7);
  }

  return {
    start: toDateInput(start),
    end: toDateInput(end),
  };
}

function getRangeByPreset(preset: '7d' | '30d' | 'month' | 'lastMonth'): DateRange {
  const end = new Date();
  const start = new Date(end);

  if (preset === '7d') {
    start.setDate(end.getDate() - 7);
  }
  if (preset === '30d') {
    start.setDate(end.getDate() - 30);
  }
  if (preset === 'month') {
    start.setDate(1);
  }
  if (preset === 'lastMonth') {
    start.setMonth(end.getMonth() - 1, 1);
    end.setDate(0);
  }

  return {
    start: toDateInput(start),
    end: toDateInput(end),
  };
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
  });
}

function getReportType(type: ReportType) {
  return REPORT_TYPES.find((item) => item.id === type) || REPORT_TYPES[0];
}

function ReportTypeGrid({
  selectedType,
  onSelect,
}: {
  selectedType: ReportType;
  onSelect: (type: ReportType) => void;
}) {
  return (
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">
      {REPORT_TYPES.map((type) => {
        const Icon = type.icon;
        const selected = selectedType === type.id;

        return (
          <button
            key={type.id}
            type="button"
            onClick={() => onSelect(type.id)}
            className={cn(
              'min-h-[124px] rounded-lg border bg-white p-4 text-left shadow-sm transition-all hover:border-primary/50 hover:shadow-md',
              selected ? 'border-primary ring-2 ring-primary/15' : 'border-border/70'
            )}
          >
            <div className="flex items-start gap-3">
              <span className={cn('flex h-10 w-10 shrink-0 items-center justify-center rounded-lg', type.tone)}>
                <Icon className="h-5 w-5" />
              </span>
              <span className="min-w-0 flex-1">
                <span className="flex items-center gap-2">
                  <span className="font-semibold text-slate-950">{type.name}</span>
                  {type.autoGenerate ? (
                    <Badge variant="secondary" className="rounded-full px-2 text-[10px]">
                      自动
                    </Badge>
                  ) : null}
                </span>
                <span className="mt-3 block text-xs leading-5 text-slate-500">{type.description}</span>
              </span>
            </div>
          </button>
        );
      })}
    </div>
  );
}

function ScopePanel({
  dateRange,
  selectedChildName,
  selectedDimensions,
  isGenerating,
  onDateRangeChange,
  onToggleDimension,
  onGenerate,
}: {
  dateRange: DateRange;
  selectedChildName: string;
  selectedDimensions: string[];
  isGenerating: boolean;
  onDateRangeChange: (range: DateRange) => void;
  onToggleDimension: (dimension: string) => void;
  onGenerate: () => void;
}) {
  return (
    <Card className="rounded-lg py-0 hover:shadow-sm">
      <CardContent className="p-5">
        <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(240px,0.8fr)_minmax(260px,1fr)]">
          <div>
            <p className="text-sm font-semibold text-slate-950">时间范围</p>
            <div className="mt-3 flex flex-wrap gap-2">
              {[
                ['近7天', '7d'],
                ['近30天', '30d'],
                ['本月', 'month'],
                ['上月', 'lastMonth'],
              ].map(([label, preset]) => (
                <Button
                  key={preset}
                  type="button"
                  variant="outline"
                  size="sm"
                  className="h-9 rounded-lg bg-white"
                  onClick={() => onDateRangeChange(getRangeByPreset(preset as '7d' | '30d' | 'month' | 'lastMonth'))}
                >
                  {label}
                </Button>
              ))}
            </div>
            <div className="mt-3 grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]">
              <DatePicker value={dateRange.start} onChange={(start) => onDateRangeChange({ ...dateRange, start })} align="start" />
              <span className="hidden self-center text-sm text-slate-400 sm:block">至</span>
              <DatePicker value={dateRange.end} onChange={(end) => onDateRangeChange({ ...dateRange, end })} align="start" />
            </div>
          </div>

          <div>
            <p className="text-sm font-semibold text-slate-950">适用对象</p>
            <div className="mt-3 flex h-10 items-center justify-between rounded-lg border border-border bg-white px-3 text-sm shadow-sm">
              <span className="flex items-center gap-2 font-medium text-slate-700">
                <UserRound className="h-4 w-4 text-slate-400" />
                {selectedChildName}
              </span>
            </div>
          </div>

          <div>
            <p className="text-sm font-semibold text-slate-950">维度选择</p>
            <div className="mt-3 flex flex-wrap gap-2">
              {DIMENSIONS.map((dimension) => {
                const active = selectedDimensions.includes(dimension);
                return (
                  <button
                    key={dimension}
                    type="button"
                    onClick={() => onToggleDimension(dimension)}
                    className={cn(
                      'rounded-full border px-3 py-1.5 text-xs font-medium transition-colors',
                      active ? 'border-primary bg-primary/10 text-primary' : 'border-border bg-white text-slate-500 hover:bg-slate-50'
                    )}
                  >
                    {dimension}
                  </button>
                );
              })}
            </div>
          </div>
        </div>

        <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center">
          <Button
            type="button"
            onClick={onGenerate}
            disabled={isGenerating}
            className="h-11 flex-1 rounded-lg"
          >
            {isGenerating ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                生成中
              </>
            ) : (
              <>
                <Sparkles className="h-4 w-4" />
                生成 AI 分析报告
              </>
            )}
          </Button>
          <Button type="button" variant="ghost" className="h-11 rounded-lg text-slate-500">
            高级设置
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

function ReportListItem({
  report,
  active,
  onOpen,
  onDelete,
  onToggleFavorite,
}: {
  report: Report;
  active: boolean;
  onOpen: () => void;
  onDelete: () => void;
  onToggleFavorite: () => void;
}) {
  const type = getReportType(report.type);
  const Icon = type.icon;

  return (
    <button
      type="button"
      onClick={onOpen}
      className={cn(
        'group flex w-full items-center gap-3 rounded-lg border p-3 text-left transition-colors',
        active ? 'border-primary bg-primary/5' : 'border-transparent hover:bg-slate-50'
      )}
    >
      <span className={cn('flex h-9 w-9 shrink-0 items-center justify-center rounded-lg', type.tone)}>
        <Icon className="h-4 w-4" />
      </span>
      <span className="min-w-0 flex-1">
        <span className="block truncate text-sm font-semibold text-slate-950">{report.title}</span>
        <span className="mt-1 block text-xs text-slate-500">生成于 {formatDate(report.createdAt)}</span>
      </span>
      <Badge className={cn('rounded-full border-0 px-2 text-[10px] shadow-none', type.badge)}>{type.shortName}</Badge>
      <span className="flex items-center gap-1 text-slate-400 opacity-0 transition-opacity group-hover:opacity-100">
        <span
          role="button"
          tabIndex={0}
          className="flex h-7 w-7 items-center justify-center rounded-md hover:bg-white hover:text-slate-700"
          onClick={(event) => {
            event.stopPropagation();
            onOpen();
          }}
        >
          <Eye className="h-4 w-4" />
        </span>
        <span
          role="button"
          tabIndex={0}
          className="flex h-7 w-7 items-center justify-center rounded-md hover:bg-white hover:text-slate-700"
          onClick={(event) => {
            event.stopPropagation();
            onToggleFavorite();
          }}
        >
          <Star className={cn('h-4 w-4', report.isFavorite ? 'fill-amber-400 text-amber-400' : '')} />
        </span>
        <span
          role="button"
          tabIndex={0}
          className="flex h-7 w-7 items-center justify-center rounded-md hover:bg-white hover:text-red-600"
          onClick={(event) => {
            event.stopPropagation();
            onDelete();
          }}
        >
          <Trash2 className="h-4 w-4" />
        </span>
      </span>
    </button>
  );
}

function ReportDetail({
  report,
  onRegenerate,
}: {
  report: Report;
  onRegenerate: () => void;
}) {
  const type = getReportType(report.type);
  const Icon = type.icon;
  const metrics = [
    { label: '完成率', value: `${report.content.dataAnalysis.completionRate}%`, tone: 'text-emerald-600' },
    { label: '完成任务', value: report.content.dataAnalysis.totalTasks, tone: 'text-blue-600' },
    { label: '学习时长', value: `${Math.round(report.content.dataAnalysis.totalTime / 60)}h`, tone: 'text-violet-600' },
  ];

  return (
    <div className="flex h-full flex-col">
      <div className="border-b border-border p-5">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div className="flex min-w-0 items-start gap-3">
            <span className={cn('flex h-11 w-11 shrink-0 items-center justify-center rounded-lg', type.tone)}>
              <Icon className="h-5 w-5" />
            </span>
            <div className="min-w-0">
              <h2 className="truncate text-lg font-semibold text-slate-950">{report.title}</h2>
              <p className="mt-1 text-sm text-slate-500">
                {report.childName || '当前孩子'} · {formatDate(report.startDate)} - {formatDate(report.endDate)}
              </p>
            </div>
          </div>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" size="sm" onClick={onRegenerate}>
              <RefreshCw className="h-4 w-4" />
              重新生成
            </Button>
            <Button variant="outline" size="sm" onClick={() => toast.info('导出能力会在报告收口阶段统一处理')}>
              <Download className="h-4 w-4" />
              导出
            </Button>
          </div>
        </div>
      </div>

      <div className="min-h-0 flex-1 overflow-y-auto p-5">
        <div className="space-y-5">
          <section className="rounded-lg border border-border bg-gradient-to-br from-indigo-50/70 via-white to-sky-50/70 p-5">
            <div className="flex gap-3">
              <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                <Sparkles className="h-5 w-5" />
              </span>
              <div>
                <h3 className="font-semibold text-slate-950">本期摘要</h3>
                <p className="mt-2 text-sm leading-6 text-slate-600">{report.content.summary}</p>
              </div>
            </div>
          </section>

          <div className="grid gap-3 md:grid-cols-3">
            {metrics.map((metric) => (
              <section key={metric.label} className="rounded-lg border border-border bg-white p-4">
                <p className="text-sm text-slate-500">{metric.label}</p>
                <p className={cn('mt-2 text-2xl font-semibold', metric.tone)}>{metric.value}</p>
              </section>
            ))}
          </div>

          <section className="rounded-lg border border-border bg-white p-5">
            <h3 className="flex items-center gap-2 font-semibold text-slate-950">
              <CheckCircle2 className="h-4 w-4 text-emerald-500" />
              关键亮点
            </h3>
            <div className="mt-4 space-y-3">
              {report.content.highlights.length > 0 ? (
                report.content.highlights.map((item) => (
                  <p key={item} className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-600">{item}</p>
                ))
              ) : (
                <p className="text-sm text-slate-500">暂无亮点内容</p>
              )}
            </div>
          </section>

          <section className="rounded-lg border border-border bg-white p-5">
            <h3 className="flex items-center gap-2 font-semibold text-slate-950">
              <GraduationCap className="h-4 w-4 text-blue-500" />
              后续建议
            </h3>
            <div className="mt-4 space-y-3">
              {report.content.suggestions.length > 0 ? (
                report.content.suggestions.map((item) => (
                  <p key={item} className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-slate-600">{item}</p>
                ))
              ) : (
                <p className="text-sm text-slate-500">暂无建议内容</p>
              )}
            </div>
          </section>

          {report.content.predictions ? (
            <section className="rounded-lg border border-border bg-white p-5">
              <h3 className="flex items-center gap-2 font-semibold text-slate-950">
                <Sparkles className="h-4 w-4 text-primary" />
                下阶段观察
              </h3>
              <p className="mt-3 text-sm leading-6 text-slate-600">{report.content.predictions}</p>
            </section>
          ) : null}
        </div>
      </div>
    </div>
  );
}

export default function ReportsPage() {
  const [selectedType, setSelectedType] = useState<ReportType>('weekly');
  const [selectedTab, setSelectedTab] = useState<'all' | ReportType>('all');
  const [dateRange, setDateRange] = useState<DateRange>(() => getRangeForType('weekly'));
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);
  const [selectedDimensions, setSelectedDimensions] = useState<string[]>(() => DIMENSIONS.slice(0, 3));
  const { selectedChildId, selectedChild } = useSelectedChild();
  const queryClient = useQueryClient();

  const { data: reports = [], isLoading } = useQuery({
    queryKey: ['reports', selectedTab, selectedChildId],
    queryFn: () => fetchReports(selectedTab === 'all' ? undefined : selectedTab, selectedChildId || undefined),
  });

  useEffect(() => {
    setDateRange(getRangeForType(selectedType));
  }, [selectedType]);

  useEffect(() => {
    if (!selectedReport) return;
    const latest = reports.find((report) => report.id === selectedReport.id);
    if (latest) {
      setSelectedReport(latest);
    }
  }, [reports, selectedReport]);

  const generateMutation = useMutation({
    mutationFn: generateReport,
    onSuccess: (newReport) => {
      toast.success('报告生成成功');
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      setSelectedReport(newReport);
    },
    onError: (error) => {
      toast.error(`生成失败：${getErrorMessage(error)}`);
    },
  });

  const deleteMutation = useMutation({
    mutationFn: deleteReport,
    onSuccess: () => {
      toast.success('报告已删除');
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      setSelectedReport(null);
    },
    onError: (error) => toast.error(`删除失败：${getErrorMessage(error)}`),
  });

  const favoriteMutation = useMutation({
    mutationFn: ({ id, isFavorite }: { id: number; isFavorite: boolean }) => toggleFavorite(id, isFavorite),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['reports'] }),
    onError: (error) => toast.error(`收藏状态更新失败：${getErrorMessage(error)}`),
  });

  const childName = selectedChild?.name || '当前孩子';
  const tabOptions = useMemo(() => [{ id: 'all' as const, name: '全部' }, ...REPORT_TYPES], []);
  const filteredReports = reports.filter((report) => (selectedTab === 'all' ? true : report.type === selectedTab));

  const handleGenerate = () => {
    if (!dateRange.start || !dateRange.end) {
      toast.error('请先选择报告时间范围');
      return;
    }

    generateMutation.mutate({
      type: selectedType,
      childId: selectedChildId || undefined,
      startDate: dateRange.start,
      endDate: dateRange.end,
      subjects: selectedDimensions,
    });
  };

  const handleToggleDimension = (dimension: string) => {
    setSelectedDimensions((current) =>
      current.includes(dimension)
        ? current.filter((item) => item !== dimension)
        : [...current, dimension]
    );
  };

  return (
    <div className="mx-auto max-w-[1360px] space-y-5">
      <PageToolbar
        left={
          <PageToolbarTitle
            icon={FileText}
            title="学习报告"
            description={`${childName}的多维度学习报告、阶段复盘和后续建议`}
          />
        }
        right={
          <Button variant="outline" className="h-11 rounded-xl bg-white">
            <Sparkles className="h-4 w-4" />
            AI 助手
          </Button>
        }
      />

      <Card className="rounded-lg py-0 hover:shadow-sm">
        <CardContent className="p-5">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-base font-semibold text-slate-950">选择报告类型</h2>
          </div>
          <ReportTypeGrid selectedType={selectedType} onSelect={setSelectedType} />
        </CardContent>
      </Card>

      <section className="space-y-3">
        <h2 className="text-base font-semibold text-slate-950">设置报告范围</h2>
        <ScopePanel
          dateRange={dateRange}
          selectedChildName={childName}
          selectedDimensions={selectedDimensions}
          isGenerating={generateMutation.isPending}
          onDateRangeChange={setDateRange}
          onToggleDimension={handleToggleDimension}
          onGenerate={handleGenerate}
        />
      </section>

      <div className="grid gap-5 xl:grid-cols-[420px_minmax(0,1fr)]">
        <Card className="min-h-[520px] rounded-lg py-0 hover:shadow-sm">
          <CardContent className="flex h-full flex-col p-5">
            <div className="mb-4 flex items-center justify-between">
              <div>
                <h2 className="text-base font-semibold text-slate-950">最近生成的报告</h2>
                <p className="mt-1 text-sm text-slate-500">按类型筛选，快速回到历史复盘。</p>
              </div>
              <Button variant="ghost" size="icon-sm" onClick={() => toast.info('更多操作会在报告收口阶段统一处理')}>
                <MoreHorizontal className="h-4 w-4" />
              </Button>
            </div>

            <div className="mb-4 flex flex-wrap gap-2">
              {tabOptions.map((item) => (
                <Button
                  key={item.id}
                  type="button"
                  variant={selectedTab === item.id ? 'default' : 'outline'}
                  size="sm"
                  className="h-9 rounded-lg"
                  onClick={() => setSelectedTab(item.id)}
                >
                  {item.name}
                </Button>
              ))}
            </div>

            <div className="min-h-0 flex-1 overflow-y-auto">
              {isLoading ? (
                <div className="space-y-3">
                  {[1, 2, 3, 4].map((item) => (
                    <Skeleton key={item} className="h-16 rounded-lg" />
                  ))}
                </div>
              ) : filteredReports.length > 0 ? (
                <div className="space-y-2">
                  {filteredReports.map((report) => (
                    <ReportListItem
                      key={report.id}
                      report={report}
                      active={selectedReport?.id === report.id}
                      onOpen={() => setSelectedReport(report)}
                      onDelete={() => deleteMutation.mutate(report.id)}
                      onToggleFavorite={() => favoriteMutation.mutate({ id: report.id, isFavorite: !report.isFavorite })}
                    />
                  ))}
                </div>
              ) : (
                <div className="flex min-h-[300px] flex-col items-center justify-center rounded-lg border border-dashed border-border bg-slate-50/70 p-8 text-center">
                  <FileText className="h-10 w-10 text-slate-300" />
                  <p className="mt-3 text-sm font-medium text-slate-700">暂无报告</p>
                  <p className="mt-1 text-sm text-slate-500">选择类型和范围后生成第一份报告。</p>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        <Card className="min-h-[520px] rounded-lg py-0 hover:shadow-sm">
          <CardContent className="h-full p-0">
            {selectedReport ? (
              <ReportDetail
                report={selectedReport}
                onRegenerate={() =>
                  generateMutation.mutate({
                    type: selectedReport.type,
                    childId: selectedReport.childId || selectedChildId || undefined,
                    startDate: selectedReport.startDate,
                    endDate: selectedReport.endDate,
                  })
                }
              />
            ) : (
              <div className="flex h-full min-h-[520px] items-center justify-center p-8">
                <div className="max-w-sm text-center">
                  <div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-primary/10 text-primary">
                    <FileText className="h-12 w-12" />
                  </div>
                  <h2 className="mt-5 text-lg font-semibold text-slate-950">选择条件生成报告</h2>
                  <p className="mt-2 text-sm leading-6 text-slate-500">选择报告类型和范围后，生成个性化学习分析报告；也可以从左侧历史报告查看详情。</p>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
