ALTER TABLE "daily_checkins"
ADD COLUMN IF NOT EXISTS "focus_minutes" INTEGER,
ADD COLUMN IF NOT EXISTS "metadata" JSONB NOT NULL DEFAULT '{}',
ADD COLUMN IF NOT EXISTS "evidence_url" VARCHAR(255) NOT NULL DEFAULT '';
